// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoccerTeamManager.Infra.Data.Contexts;

#nullable disable

namespace SoccerTeamManager.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220724194846_first migration")]
    partial class firstmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SoccerTeamManager.Domain.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Country", "manager");

                    b.HasData(
                        new
                        {
                            Id = new Guid("74f976f5-97d3-4829-9066-039fb574938b"),
                            Name = "Afeganistão"
                        },
                        new
                        {
                            Id = new Guid("27b43733-4a18-457b-b351-24bf9342c85e"),
                            Name = "África do Sul"
                        },
                        new
                        {
                            Id = new Guid("00e5d5b8-8068-4b71-b845-b2ba31844372"),
                            Name = "Albânia"
                        },
                        new
                        {
                            Id = new Guid("f6044414-e105-447a-8e6e-23305312bdf4"),
                            Name = "Alemanha"
                        },
                        new
                        {
                            Id = new Guid("45dac392-0617-4aa3-9b89-b1f9111a15e2"),
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = new Guid("e2f19816-b102-49ef-8621-98f62417ab79"),
                            Name = "Angola"
                        },
                        new
                        {
                            Id = new Guid("46b43b0f-b112-459a-bd6c-db23b5b1b6f0"),
                            Name = "Antígua e Barbuda"
                        },
                        new
                        {
                            Id = new Guid("ff124944-1857-4966-846b-1b383fc52108"),
                            Name = "Arábia Saudita"
                        },
                        new
                        {
                            Id = new Guid("b1da1d6d-918a-46de-b58a-a00de674c394"),
                            Name = "Argélia"
                        },
                        new
                        {
                            Id = new Guid("220d14c3-1e13-435b-b61c-c9e550efc78d"),
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = new Guid("70f36751-e881-426e-85f0-975575604047"),
                            Name = "Arménia"
                        },
                        new
                        {
                            Id = new Guid("9d19150a-3031-4d2a-bde4-5c85791c7d20"),
                            Name = "Austrália"
                        },
                        new
                        {
                            Id = new Guid("540e51a9-ad3f-41e2-a43c-ccea29e00e29"),
                            Name = "Áustria"
                        },
                        new
                        {
                            Id = new Guid("168a1966-44b5-42ab-915d-f38fd98ed15f"),
                            Name = "Azerbaijão"
                        },
                        new
                        {
                            Id = new Guid("b8fa010a-af34-4112-9141-3a8913398ae7"),
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = new Guid("584082a4-d598-4213-bd5d-d6169129c148"),
                            Name = "Bahrein"
                        },
                        new
                        {
                            Id = new Guid("76565a86-479c-417a-99fe-ab1e86e1da0c"),
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = new Guid("98b524af-9652-42f9-93cb-029a2dac6b93"),
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = new Guid("ef80fdca-b078-4f14-9261-1ff1df966d1a"),
                            Name = "Bélgica"
                        },
                        new
                        {
                            Id = new Guid("b5072123-2daa-4af2-aab3-f889e90de30e"),
                            Name = "Belize"
                        },
                        new
                        {
                            Id = new Guid("d57bd05d-8fa3-4860-b32d-7df88b10fc25"),
                            Name = "Benim"
                        },
                        new
                        {
                            Id = new Guid("33f80a4e-94de-4d30-9271-feec67dec0a3"),
                            Name = "Bielorrússia"
                        },
                        new
                        {
                            Id = new Guid("c7b51974-e637-433a-a6c4-e81a6323418f"),
                            Name = "Bolívia"
                        },
                        new
                        {
                            Id = new Guid("7ff8f1a0-8597-41a1-a6f9-a9804c1ba17b"),
                            Name = "Bósnia e Herzegovina"
                        },
                        new
                        {
                            Id = new Guid("13de203a-ff82-42c9-9161-df6239db79b1"),
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = new Guid("c3ff1054-b6b1-4d10-a69d-4ab584c6bf6c"),
                            Name = "Brasil"
                        },
                        new
                        {
                            Id = new Guid("c0163725-b0ab-4975-9b99-cc39fca83ac1"),
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = new Guid("e30d86b3-d072-4223-8257-d574d96c72f4"),
                            Name = "Bulgária"
                        },
                        new
                        {
                            Id = new Guid("8d698e06-11c6-4bf3-97ff-89abd73c0378"),
                            Name = "Burquina Fasso"
                        },
                        new
                        {
                            Id = new Guid("b3bb3865-f7ac-4ddc-9d1e-e60a85ed42b8"),
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = new Guid("9b93607b-eea9-4f5d-9e12-2cdf881dca2f"),
                            Name = "Butão"
                        },
                        new
                        {
                            Id = new Guid("d01de4da-8832-4690-873d-10c935aefd2a"),
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = new Guid("a81660ef-71ea-4d5f-b692-65c908ba0b3d"),
                            Name = "Camarões"
                        },
                        new
                        {
                            Id = new Guid("a68a38fc-4bd4-44be-a497-b6d2a232eacb"),
                            Name = "Camboja"
                        },
                        new
                        {
                            Id = new Guid("9c758af6-f29e-4467-bbd3-1914777af329"),
                            Name = "Canadá"
                        },
                        new
                        {
                            Id = new Guid("6bd09f91-560f-47ae-8634-f643f42cebd6"),
                            Name = "Catar"
                        },
                        new
                        {
                            Id = new Guid("fdcfe383-1ae4-4a1a-a13d-e549dda731c2"),
                            Name = "Cazaquistão"
                        },
                        new
                        {
                            Id = new Guid("d3e9c4d3-f026-45b1-8918-257b83e83c07"),
                            Name = "Chade"
                        },
                        new
                        {
                            Id = new Guid("7fa01317-dbdb-4de8-92c7-3d93b4aec9b6"),
                            Name = "Chéquia"
                        },
                        new
                        {
                            Id = new Guid("32a7dfb7-9c6b-422a-8ed1-f517779a35ae"),
                            Name = "Chile"
                        },
                        new
                        {
                            Id = new Guid("31e01861-302e-4043-8053-93e657283e0b"),
                            Name = "China"
                        },
                        new
                        {
                            Id = new Guid("b9f4148a-5de9-42c7-bfed-50a4b7fb10c6"),
                            Name = "Chipre"
                        },
                        new
                        {
                            Id = new Guid("8c3b3c6d-3a92-4521-af49-63b8f5beac2f"),
                            Name = "Colômbia"
                        },
                        new
                        {
                            Id = new Guid("fd47067b-30d1-459b-95e0-e5dbea643f50"),
                            Name = "Comores"
                        },
                        new
                        {
                            Id = new Guid("1679fe4c-aa38-4133-84a2-d5bfbba8d2cc"),
                            Name = "Congo"
                        },
                        new
                        {
                            Id = new Guid("879ca88f-ec5f-47b5-8afb-8440fca390aa"),
                            Name = "Coreia do Norte"
                        },
                        new
                        {
                            Id = new Guid("5e033453-5b83-4018-aab2-c45d247d332a"),
                            Name = "Coreia do Sul"
                        },
                        new
                        {
                            Id = new Guid("775c47e5-f7a1-4d7f-ac0f-be458553d8cb"),
                            Name = "Costa do Marfim"
                        },
                        new
                        {
                            Id = new Guid("4f690532-b31e-4849-a101-fe3dc4721729"),
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = new Guid("7cb4aba3-d2b4-4f8e-bc62-9e67684b2d72"),
                            Name = "Croácia"
                        },
                        new
                        {
                            Id = new Guid("51c134e3-fe74-4784-84df-ab6505c13c81"),
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = new Guid("e14140f6-030c-428f-9daa-d8a19bd7134c"),
                            Name = "Dinamarca"
                        },
                        new
                        {
                            Id = new Guid("70dd5979-a466-4434-8168-680b80fb9952"),
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = new Guid("4bc4f063-d2f0-404f-b9be-aded85e8fb70"),
                            Name = "Domínica"
                        },
                        new
                        {
                            Id = new Guid("2bedc06b-9c54-4bd0-a386-74efb3a0f7a6"),
                            Name = "Egito"
                        },
                        new
                        {
                            Id = new Guid("8fe39b2c-8b61-4b8a-b98d-39153828d198"),
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = new Guid("4764f32d-6cc2-4d8a-ab01-e91f1f63367d"),
                            Name = "Emirados Árabes Unidos"
                        },
                        new
                        {
                            Id = new Guid("336d26bd-0fd8-472f-9a56-cd86cf3a4ea3"),
                            Name = "Equador"
                        },
                        new
                        {
                            Id = new Guid("2d30360d-4ac7-425c-9ebd-d926bd689ac8"),
                            Name = "Eritreia"
                        },
                        new
                        {
                            Id = new Guid("0cd4f6f1-ac99-4e35-a250-7289079705b3"),
                            Name = "Eslováquia"
                        },
                        new
                        {
                            Id = new Guid("a5e572bb-42bc-49e3-b81d-c3ba66d9dbb5"),
                            Name = "Eslovénia"
                        },
                        new
                        {
                            Id = new Guid("d5b3a5ea-717c-4a26-bff4-502b6fc80dc4"),
                            Name = "Espanha"
                        },
                        new
                        {
                            Id = new Guid("bcd73797-ab01-4980-bff3-743a0893554a"),
                            Name = "Estados Federados da Micronésia"
                        },
                        new
                        {
                            Id = new Guid("f2b93b1c-fe13-459d-bee1-bb0217cb73db"),
                            Name = "Estados Unidos"
                        },
                        new
                        {
                            Id = new Guid("dc88c5d7-c207-4887-bf11-f90b21e18d1e"),
                            Name = "Estónia"
                        },
                        new
                        {
                            Id = new Guid("9bb2b900-51a8-42ba-8afc-fd341a26e71c"),
                            Name = "Eswatini"
                        },
                        new
                        {
                            Id = new Guid("095d2bd6-a470-466b-9f69-28688c321135"),
                            Name = "Etiópia"
                        },
                        new
                        {
                            Id = new Guid("f9dd348b-ec92-410b-84ea-fcce72d6ebf0"),
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = new Guid("cd8a4f9a-a3d0-4a44-8a24-355fbba96f3b"),
                            Name = "Filipinas"
                        },
                        new
                        {
                            Id = new Guid("6e5f6a44-0c70-4ae8-9fd3-fa65ff101648"),
                            Name = "Finlândia"
                        },
                        new
                        {
                            Id = new Guid("4cbadb5d-b125-455d-b6e9-a0529c6a43a1"),
                            Name = "França"
                        },
                        new
                        {
                            Id = new Guid("d9c80cbd-d856-400a-bab0-7434c9724f26"),
                            Name = "Gabão"
                        },
                        new
                        {
                            Id = new Guid("6bdc3ea6-af88-47c8-8c13-c6a1e1cda841"),
                            Name = "Gâmbia"
                        },
                        new
                        {
                            Id = new Guid("1d30f1a5-be50-42ff-aa27-817625af4d3a"),
                            Name = "Gana"
                        },
                        new
                        {
                            Id = new Guid("3bfa7236-e0d8-4a84-8597-f21d20650c68"),
                            Name = "Geórgia"
                        },
                        new
                        {
                            Id = new Guid("391cebd1-0f01-4e6c-bf83-a6525de95d9f"),
                            Name = "Granada"
                        },
                        new
                        {
                            Id = new Guid("2911f66f-2387-4f47-bbf4-c5b9b7914061"),
                            Name = "Grécia"
                        },
                        new
                        {
                            Id = new Guid("c10f30f5-c5f2-4763-823e-5add75e5a22f"),
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = new Guid("51dd00bc-7eb0-4051-8933-f205ce9cb86c"),
                            Name = "Guiana"
                        },
                        new
                        {
                            Id = new Guid("0d1f3ead-0262-43bf-b813-0eadac337814"),
                            Name = "Guiné"
                        },
                        new
                        {
                            Id = new Guid("ca7c396c-b782-44b1-adee-0b84f2782108"),
                            Name = "Guiné Equatorial"
                        },
                        new
                        {
                            Id = new Guid("119d39bc-4ac7-405c-9afd-3de2fc1aeb41"),
                            Name = "Guiné-Bissau"
                        },
                        new
                        {
                            Id = new Guid("77e0c6eb-0513-4bc6-b98b-941f21a599bf"),
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = new Guid("7137cbb1-e693-4e4b-b113-ffe6ffbfdcd2"),
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = new Guid("633590bc-fba7-4ae5-80b0-7f27b8eb14ec"),
                            Name = "Hungria"
                        },
                        new
                        {
                            Id = new Guid("5a582021-4c94-4850-95ba-9ae51d227fdf"),
                            Name = "Iémen"
                        },
                        new
                        {
                            Id = new Guid("7c6bd35c-e9a8-4341-a194-b34802723ce0"),
                            Name = "Ilhas Cook"
                        },
                        new
                        {
                            Id = new Guid("83b30064-8abb-4dd3-9fc6-d2010e70dad9"),
                            Name = "Ilhas Marshall"
                        },
                        new
                        {
                            Id = new Guid("bf6b9bf9-f374-4081-a581-a47d50ae454f"),
                            Name = "Ilhas Salomão"
                        },
                        new
                        {
                            Id = new Guid("49c91c4f-d494-41ee-b055-e3e05b1ef387"),
                            Name = "Índia"
                        },
                        new
                        {
                            Id = new Guid("7c7f0231-1f8f-4204-abde-42e90805aa10"),
                            Name = "Indonésia"
                        },
                        new
                        {
                            Id = new Guid("e7efd9b9-1510-4ca5-85cb-b339851eb29f"),
                            Name = "Irã"
                        },
                        new
                        {
                            Id = new Guid("528ba571-103a-4281-bd6b-14b5497a9fbb"),
                            Name = "Iraque"
                        },
                        new
                        {
                            Id = new Guid("db0ce644-0ace-483c-83bb-1e7a2ace9f1e"),
                            Name = "Irlanda"
                        },
                        new
                        {
                            Id = new Guid("00991368-53d0-4330-9c8e-845255f75528"),
                            Name = "Islândia"
                        },
                        new
                        {
                            Id = new Guid("4ce69068-1117-4084-a741-283fec883afb"),
                            Name = "Israel"
                        },
                        new
                        {
                            Id = new Guid("e7885114-20fd-4341-aa23-7a0256b6763f"),
                            Name = "Itália"
                        },
                        new
                        {
                            Id = new Guid("43229c73-1bb4-41f5-8c97-f6ab98fd27ca"),
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = new Guid("c8113511-b443-48f3-a056-4b24fa60b1e4"),
                            Name = "Japão"
                        },
                        new
                        {
                            Id = new Guid("5aa48457-e238-4d83-9a43-0b66621617ac"),
                            Name = "Jordânia"
                        },
                        new
                        {
                            Id = new Guid("0f3f4548-9509-46eb-9560-2a05acc167df"),
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = new Guid("b994a324-b7ef-4ed5-9d49-dabf071acc7c"),
                            Name = "Kosovo"
                        },
                        new
                        {
                            Id = new Guid("54b2e832-0b62-49a5-9115-3e711616a28e"),
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = new Guid("c455146b-19aa-45f9-b5e1-869f4512300c"),
                            Name = "Laos"
                        },
                        new
                        {
                            Id = new Guid("d663bffe-8ec4-4b9c-b399-5bfe5d3f2daa"),
                            Name = "Lesoto"
                        },
                        new
                        {
                            Id = new Guid("36d61e9e-8e62-4082-bec6-6211c5f4d18b"),
                            Name = "Letónia"
                        },
                        new
                        {
                            Id = new Guid("45075423-6f2b-48b3-9c2d-d742e3e49ce8"),
                            Name = "Líbano"
                        },
                        new
                        {
                            Id = new Guid("5db97174-312a-4a03-9fae-43dc53263729"),
                            Name = "Libéria"
                        },
                        new
                        {
                            Id = new Guid("4f1bf909-02f5-418b-80bf-d96e4d69c5bf"),
                            Name = "Líbia"
                        },
                        new
                        {
                            Id = new Guid("147d8fd0-aaf5-4b6b-9293-7da24b3755e6"),
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = new Guid("070f5e16-3097-4a1d-a0aa-575d072f6c0f"),
                            Name = "Lituânia"
                        },
                        new
                        {
                            Id = new Guid("48914052-1b5a-4f14-ad89-1ae4acc632ab"),
                            Name = "Luxemburgo"
                        },
                        new
                        {
                            Id = new Guid("bea3d1ae-5911-413c-bdfd-2c004fcf9cd8"),
                            Name = "Macedônia do Norte"
                        },
                        new
                        {
                            Id = new Guid("9ef4b377-17cf-4df7-989e-81c5d9efd5ce"),
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = new Guid("8bc3a114-d23c-4c82-aae5-51839147fdf3"),
                            Name = "Malásia"
                        },
                        new
                        {
                            Id = new Guid("882c73fb-bd56-4a8e-a4f6-d5052a48c11b"),
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = new Guid("62fd3f65-35b8-4fe7-b589-fefa18acc66c"),
                            Name = "Maldivas"
                        },
                        new
                        {
                            Id = new Guid("2f96fbcf-5b3d-4c11-9622-84e2c4dd4f16"),
                            Name = "Mali"
                        },
                        new
                        {
                            Id = new Guid("55f1d300-d8de-41ab-a4ae-428a4b97e92b"),
                            Name = "Malta"
                        },
                        new
                        {
                            Id = new Guid("a1bf80cb-5e25-4810-8606-84d2b02f58a9"),
                            Name = "Marrocos"
                        },
                        new
                        {
                            Id = new Guid("c090c589-8723-4c07-9451-eae5cc7ac14e"),
                            Name = "Maurícia"
                        },
                        new
                        {
                            Id = new Guid("ebb552ee-8f95-48d6-a897-56c17d1379c8"),
                            Name = "Mauritânia"
                        },
                        new
                        {
                            Id = new Guid("4ebaddd0-fc98-43fb-ae6d-f79898597bab"),
                            Name = "México"
                        },
                        new
                        {
                            Id = new Guid("cc9b146c-72d9-42b7-88c1-69c4463153d0"),
                            Name = "Moçambique"
                        },
                        new
                        {
                            Id = new Guid("315c6b66-92aa-492c-b9e7-1d54646d7b5a"),
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = new Guid("a9a601d0-0815-4db1-b936-4599159d8611"),
                            Name = "Mónaco"
                        },
                        new
                        {
                            Id = new Guid("2230da33-01dc-4943-acc8-db864c689aaf"),
                            Name = "Mongólia"
                        },
                        new
                        {
                            Id = new Guid("9f1bb5b2-43dc-4283-aec5-0965eb5f6541"),
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = new Guid("7b9f3378-9969-4870-a065-76f385b99b95"),
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = new Guid("74c835cf-e427-4a39-8056-025a1cf26ed8"),
                            Name = "Namíbia"
                        },
                        new
                        {
                            Id = new Guid("966e2fa6-c405-465c-a309-dba8726bba1a"),
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = new Guid("1b085c81-6f84-4565-be4c-2b58a6726846"),
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = new Guid("d4d83b4b-7617-4b50-9069-e55792b6cba3"),
                            Name = "Nicarágua"
                        },
                        new
                        {
                            Id = new Guid("27ae81d9-9bf4-4195-8655-1ad6f492252d"),
                            Name = "Níger"
                        },
                        new
                        {
                            Id = new Guid("1f22ccc9-5c01-4822-878e-3667b42ef45a"),
                            Name = "Nigéria"
                        },
                        new
                        {
                            Id = new Guid("a6f038bc-9b31-4aff-ba95-06f8deee54d3"),
                            Name = "Niue"
                        },
                        new
                        {
                            Id = new Guid("a1003dd4-69db-4554-83ea-491a1bff0966"),
                            Name = "Noruega"
                        },
                        new
                        {
                            Id = new Guid("0f244428-36e9-4cf6-8657-d369a2f09a3a"),
                            Name = "Nova Zelândia"
                        },
                        new
                        {
                            Id = new Guid("b5b16750-b2a8-4463-95b7-9434027ce17b"),
                            Name = "Oman"
                        },
                        new
                        {
                            Id = new Guid("57be866b-ec21-48eb-b2f7-df09a4c32bb6"),
                            Name = "Países Baixos"
                        },
                        new
                        {
                            Id = new Guid("6481e21b-e815-40fd-997a-a3baa82bdb45"),
                            Name = "Palau"
                        },
                        new
                        {
                            Id = new Guid("6ea03f9b-68d7-4f97-b53b-067517633830"),
                            Name = "Palestina"
                        },
                        new
                        {
                            Id = new Guid("936d1675-d34c-4bc1-8ad5-85380c607142"),
                            Name = "Panamá"
                        },
                        new
                        {
                            Id = new Guid("ec396596-10a3-4b11-a855-3a23a884002f"),
                            Name = "Papua-Nova Guiné"
                        },
                        new
                        {
                            Id = new Guid("2e03c212-8790-449f-9214-011911071547"),
                            Name = "Paquistão"
                        },
                        new
                        {
                            Id = new Guid("b4270269-9b71-41eb-be5b-9758b9d6f584"),
                            Name = "Paraguai"
                        },
                        new
                        {
                            Id = new Guid("6e7c53b0-e03f-4a79-9381-5ebb8c96ff60"),
                            Name = "Peru"
                        },
                        new
                        {
                            Id = new Guid("db2d7dcd-217a-42b0-ba60-e297418aa5fc"),
                            Name = "Polónia"
                        },
                        new
                        {
                            Id = new Guid("45eb3af2-2179-49c4-9229-62fac06d15f1"),
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = new Guid("fd6f11e7-38fc-48f7-9295-c298c528388c"),
                            Name = "Quénia"
                        },
                        new
                        {
                            Id = new Guid("0879c72a-509f-4ff8-9115-bc753b0d617e"),
                            Name = "Quirguistão"
                        },
                        new
                        {
                            Id = new Guid("4dd7774d-54a6-4ba7-8bdd-4ba994015c5f"),
                            Name = "Reino Unido"
                        },
                        new
                        {
                            Id = new Guid("ea8ea1c2-50c3-49f9-bb20-94f7c36146f4"),
                            Name = "República Centro-Africana"
                        },
                        new
                        {
                            Id = new Guid("ca071d1e-47ce-403e-94c8-5d9a226eccf7"),
                            Name = "República Democrática do Congo"
                        },
                        new
                        {
                            Id = new Guid("9bb6d729-bc7c-426e-bc20-29cd7094c13e"),
                            Name = "República Dominicana"
                        },
                        new
                        {
                            Id = new Guid("1f654aa3-ccff-49b9-b707-c4a5770f46fe"),
                            Name = "Roménia"
                        },
                        new
                        {
                            Id = new Guid("50391ece-28cb-4229-8538-15ccdf7e0f69"),
                            Name = "Ruanda"
                        },
                        new
                        {
                            Id = new Guid("e9a95b4b-c527-45c4-acae-87a05f1c621e"),
                            Name = "Rússia"
                        },
                        new
                        {
                            Id = new Guid("a37b3dec-cb00-4134-aadf-caf98947aab2"),
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = new Guid("68e160ff-fc89-4487-b9df-d29f3561a21d"),
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = new Guid("64497306-3478-43e8-aee1-e147f23c29ac"),
                            Name = "São Cristóvão e Nevis"
                        },
                        new
                        {
                            Id = new Guid("342fc316-d2df-4496-a86e-45a594a1dcd3"),
                            Name = "São Tomé e Príncipe"
                        },
                        new
                        {
                            Id = new Guid("02fb11d6-44a3-4d83-8dab-cfef104d8a65"),
                            Name = "São Vicente e Granadinas"
                        },
                        new
                        {
                            Id = new Guid("da6fdeb8-4d1a-47e6-a29a-bed08bb4d806"),
                            Name = "Seicheles"
                        },
                        new
                        {
                            Id = new Guid("a22f7f05-1e70-432b-83c8-1ca9f0c02e8f"),
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = new Guid("f687ba94-af29-457e-9be5-026fc7cc5145"),
                            Name = "Serra Leoa"
                        },
                        new
                        {
                            Id = new Guid("93510797-3613-4d63-ae5a-12263bac31dd"),
                            Name = "Sérvia"
                        },
                        new
                        {
                            Id = new Guid("33ad93ac-da3b-4774-bfc4-11bb1263c748"),
                            Name = "Singapura"
                        },
                        new
                        {
                            Id = new Guid("14472b5b-2f1d-4918-b93f-d78c117ac5ba"),
                            Name = "Síria"
                        },
                        new
                        {
                            Id = new Guid("cb141323-8763-4884-8793-9439663dc4e6"),
                            Name = "Somália"
                        },
                        new
                        {
                            Id = new Guid("ea73113f-8da6-4c5d-80d2-425f0fd6687f"),
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = new Guid("24689ab8-5446-4343-b328-977f7359ee22"),
                            Name = "Sudão"
                        },
                        new
                        {
                            Id = new Guid("bb367dca-a3a0-4901-8d9f-d33713a3d717"),
                            Name = "Sudão do Sul"
                        },
                        new
                        {
                            Id = new Guid("f2079f97-7806-45cc-a134-96fa9768efb5"),
                            Name = "Suécia"
                        },
                        new
                        {
                            Id = new Guid("36fc336a-c3ba-4994-a1f3-5cc9c1c0c046"),
                            Name = "Suíça"
                        },
                        new
                        {
                            Id = new Guid("515b4eaf-5bd4-458e-8adb-65fdf8531ebd"),
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = new Guid("db155c1b-5c28-46d3-8f37-5752f938b822"),
                            Name = "Tailândia"
                        },
                        new
                        {
                            Id = new Guid("21fe3f6e-8afa-4dcb-9046-246eb944933f"),
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = new Guid("68607d3c-5c75-49d5-b10f-3000e00f62f4"),
                            Name = "Tajiquistão"
                        },
                        new
                        {
                            Id = new Guid("8ab75f0e-0112-419f-b438-251de1fabaac"),
                            Name = "Tanzânia"
                        },
                        new
                        {
                            Id = new Guid("8a1ea897-03a1-493e-bc9e-87c25e7967cd"),
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = new Guid("4ff84a83-5a5f-430f-8ae5-be22f276ad01"),
                            Name = "Togo"
                        },
                        new
                        {
                            Id = new Guid("1a8014e6-ee2a-47b4-b068-d02e42e20f56"),
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = new Guid("396be8ae-0580-4689-a8ed-17d3a3f03317"),
                            Name = "Trinidad e Tobago"
                        },
                        new
                        {
                            Id = new Guid("0f43e3c9-4aef-4b9d-80ba-39625d4fe57c"),
                            Name = "Tunísia"
                        },
                        new
                        {
                            Id = new Guid("013de31c-4205-45eb-9ff5-f1e37f1585c1"),
                            Name = "Turquemenistão"
                        },
                        new
                        {
                            Id = new Guid("49c235e4-0edf-40d3-9e6f-a7ff3793a3b3"),
                            Name = "Turquia"
                        },
                        new
                        {
                            Id = new Guid("25d5922a-10e5-4033-9e5d-3de96c26bdf9"),
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = new Guid("02b2f401-c49b-49c2-a0ca-dee20ad4e914"),
                            Name = "Ucrânia"
                        },
                        new
                        {
                            Id = new Guid("3c897ea8-ca5d-4b21-b17d-7de8a9eaaedf"),
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = new Guid("d0f1febc-1b4b-42d5-8896-d9e65e2f1605"),
                            Name = "Uruguai"
                        },
                        new
                        {
                            Id = new Guid("7eef5b51-1ad9-4672-8477-5b7c4c6fd149"),
                            Name = "Uzbequistão"
                        },
                        new
                        {
                            Id = new Guid("b56be92f-26cd-4b70-8684-9e8fe72d4614"),
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = new Guid("65016704-8a3a-4158-8554-be4c32419e5c"),
                            Name = "Vaticano"
                        },
                        new
                        {
                            Id = new Guid("99ef42d7-c2e2-46fb-961b-c15b80ec1a90"),
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = new Guid("fb2c3e0a-7840-4a0f-bc3e-6d0f3f2cf7d7"),
                            Name = "Vietname"
                        },
                        new
                        {
                            Id = new Guid("aafa7339-c327-4be7-8e5c-172a64d2bd13"),
                            Name = "Zâmbia"
                        },
                        new
                        {
                            Id = new Guid("ba24229a-dd47-4991-98dc-2450913655f2"),
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("SoccerTeamManager.Domain.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("VisitorTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("TournamentId");

                    b.HasIndex("VisitorTeamId");

                    b.ToTable("Match", "manager");
                });

            modelBuilder.Entity("SoccerTeamManager.Domain.Entities.MatchEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeOfOccurrence")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("TeamId");

                    b.ToTable("MatchEvent", "manager");
                });

            modelBuilder.Entity("SoccerTeamManager.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CurrentTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("CurrentTeamId");

                    b.ToTable("Player", "manager");
                });

            modelBuilder.Entity("SoccerTeamManager.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.ToTable("Team", "manager");
                });

            modelBuilder.Entity("SoccerTeamManager.Domain.Entities.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<double>("Prize")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tournament", "manager");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4ca3cc49-f22d-4cce-aaf6-61011dea48fd"),
                            CreatedAt = new DateTime(2022, 7, 24, 16, 48, 45, 876, DateTimeKind.Local).AddTicks(2329),
                            Name = "Amistoso",
                            Prize = 0.0
                        });
                });

            modelBuilder.Entity("SoccerTeamManager.Domain.Entities.TournamentTeam", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TeamId", "TournamentId");

                    b.HasIndex("TournamentId");

                    b.ToTable("TounamentTeam", "manager");
                });

            modelBuilder.Entity("SoccerTeamManager.Domain.Entities.Transfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Ammount")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DestinationTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OriginTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DestinationTeamId");

                    b.HasIndex("OriginTeamId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Transfer", "manager");
                });

            modelBuilder.Entity("SoccerTeamManager.Domain.Entities.Match", b =>
                {
                    b.HasOne("SoccerTeamManager.Domain.Entities.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SoccerTeamManager.Domain.Entities.Tournament", null)
                        .WithMany("Matches")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoccerTeamManager.Domain.Entities.Team", "VisitorTeam")
                        .WithMany()
                        .HasForeignKey("VisitorTeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HomeTeam");

                    b.Navigation("VisitorTeam");
                });

            modelBuilder.Entity("SoccerTeamManager.Domain.Entities.MatchEvent", b =>
                {
                    b.HasOne("SoccerTeamManager.Domain.Entities.Match", null)
                        .WithMany("MatchEvents")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoccerTeamManager.Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("SoccerTeamManager.Domain.Entities.Player", b =>
                {
                    b.HasOne("SoccerTeamManager.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoccerTeamManager.Domain.Entities.Team", null)
                        .WithMany("Players")
                        .HasForeignKey("CurrentTeamId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("SoccerTeamManager.Domain.Entities.TournamentTeam", b =>
                {
                    b.HasOne("SoccerTeamManager.Domain.Entities.Team", "Team")
                        .WithMany("TournamentTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SoccerTeamManager.Domain.Entities.Tournament", "Tournament")
                        .WithMany("TournamentTeams")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("SoccerTeamManager.Domain.Entities.Transfer", b =>
                {
                    b.HasOne("SoccerTeamManager.Domain.Entities.Team", "DestinationTeam")
                        .WithMany()
                        .HasForeignKey("DestinationTeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SoccerTeamManager.Domain.Entities.Team", "OriginTeam")
                        .WithMany()
                        .HasForeignKey("OriginTeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SoccerTeamManager.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DestinationTeam");

                    b.Navigation("OriginTeam");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("SoccerTeamManager.Domain.Entities.Match", b =>
                {
                    b.Navigation("MatchEvents");
                });

            modelBuilder.Entity("SoccerTeamManager.Domain.Entities.Team", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("TournamentTeams");
                });

            modelBuilder.Entity("SoccerTeamManager.Domain.Entities.Tournament", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("TournamentTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
