// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoccerTeamManager.Infra.Data.Contexts;

#nullable disable

namespace SoccerTeamManager.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220724202601_second migration")]
    partial class secondmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SoccerTeamManager.Domain.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Country", "manager");

                    b.HasData(
                        new
                        {
                            Id = new Guid("65eb81f8-db1e-4163-9c90-bb4fd9b65f94"),
                            Name = "Papua-Nova Guiné"
                        },
                        new
                        {
                            Id = new Guid("670e56c4-d7e6-44ce-ac37-a88b55abdc21"),
                            Name = "Kosovo"
                        },
                        new
                        {
                            Id = new Guid("67e75916-9db0-4623-bcfc-1ee3ef225029"),
                            Name = "Quénia"
                        },
                        new
                        {
                            Id = new Guid("68636bfc-ed88-4023-89b3-03e2383e860d"),
                            Name = "Líbia"
                        },
                        new
                        {
                            Id = new Guid("69a7d8ea-dd3d-4800-a478-a3c4975ae04b"),
                            Name = "Islândia"
                        },
                        new
                        {
                            Id = new Guid("69fbcd91-5fdd-4398-ade6-74df53dad48b"),
                            Name = "Estados Federados da Micronésia"
                        },
                        new
                        {
                            Id = new Guid("6a151a4c-567c-400d-aa4a-2d0750058a53"),
                            Name = "Arábia Saudita"
                        },
                        new
                        {
                            Id = new Guid("6ad0f8f0-aee4-4fd5-92d9-d445de116ad5"),
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = new Guid("6b460187-bd37-4f7a-96aa-2d3980dc8418"),
                            Name = "Luxemburgo"
                        },
                        new
                        {
                            Id = new Guid("6eec0fb5-a995-4ade-a1f0-8cca506252b7"),
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = new Guid("702ee59c-5c61-454f-a02e-16f82ad4eb9f"),
                            Name = "Eswatini"
                        },
                        new
                        {
                            Id = new Guid("724dbf2f-6109-4485-9d82-15c5ca43a0f7"),
                            Name = "Malta"
                        },
                        new
                        {
                            Id = new Guid("73e37f95-c007-4241-9ab0-88c38f65fdae"),
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = new Guid("74e11c70-9ee3-4489-9ec1-08fcaea6c657"),
                            Name = "Mauritânia"
                        },
                        new
                        {
                            Id = new Guid("78b121a9-8ac7-4f56-b957-cb05c025a406"),
                            Name = "Domínica"
                        },
                        new
                        {
                            Id = new Guid("7da4a0de-602e-438c-833f-c6b50800cb21"),
                            Name = "Austrália"
                        },
                        new
                        {
                            Id = new Guid("7f1a9f2e-f553-43d2-998b-e36179c9cbca"),
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = new Guid("7fa499d5-9d50-4b6c-a02f-27c26c1dd40f"),
                            Name = "Somália"
                        },
                        new
                        {
                            Id = new Guid("810ea211-0535-4288-8067-0466f9550310"),
                            Name = "China"
                        },
                        new
                        {
                            Id = new Guid("828d09b5-187b-4415-a979-ee691962bc8a"),
                            Name = "Bolívia"
                        },
                        new
                        {
                            Id = new Guid("84d9fa82-b5b6-47c0-9690-16e5f265007e"),
                            Name = "Nicarágua"
                        },
                        new
                        {
                            Id = new Guid("853efbe3-75cb-41b7-96e7-b466a3bd9ba2"),
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = new Guid("85ec7243-657e-40a1-9ea5-a342da6a4083"),
                            Name = "Chade"
                        },
                        new
                        {
                            Id = new Guid("86f31fb5-9863-4849-beae-83dacc7c478c"),
                            Name = "Belize"
                        },
                        new
                        {
                            Id = new Guid("88913b51-73a3-4114-a1b5-594c106b6a1c"),
                            Name = "Ilhas Marshall"
                        },
                        new
                        {
                            Id = new Guid("89069f8b-147a-4ab8-ad56-b4e58a4dc88b"),
                            Name = "Turquemenistão"
                        },
                        new
                        {
                            Id = new Guid("8d53cbcf-af1d-4cdf-ab4e-ef2ef2d873a4"),
                            Name = "Angola"
                        },
                        new
                        {
                            Id = new Guid("8f339194-7212-44d6-935e-70c239cdf6de"),
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = new Guid("902d4625-119b-491c-a289-2ccb9b860383"),
                            Name = "Arménia"
                        },
                        new
                        {
                            Id = new Guid("9080fd90-c32d-4207-b3f0-ec37ae5f10e9"),
                            Name = "Catar"
                        },
                        new
                        {
                            Id = new Guid("911bfb62-c7b0-463f-bf1d-acb1d6f54efa"),
                            Name = "Eslovénia"
                        },
                        new
                        {
                            Id = new Guid("92b07193-e02a-4f31-8f5f-5804c521402d"),
                            Name = "Moçambique"
                        },
                        new
                        {
                            Id = new Guid("93810913-c821-4250-8946-6149203c786e"),
                            Name = "Alemanha"
                        },
                        new
                        {
                            Id = new Guid("9654f610-391c-45f9-bcfe-2a5018bf159b"),
                            Name = "Guiana"
                        },
                        new
                        {
                            Id = new Guid("9672c08a-66b1-4c00-ad35-d9fdf958ba7f"),
                            Name = "Oman"
                        },
                        new
                        {
                            Id = new Guid("98cbe07c-effd-4b45-853f-663ba2ca9ac4"),
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = new Guid("99b07b59-2568-4856-9bf4-1aed5e4aaaa3"),
                            Name = "Reino Unido"
                        },
                        new
                        {
                            Id = new Guid("99c265f2-dc54-4f7b-bdf8-9bc9fd6d45a7"),
                            Name = "Azerbaijão"
                        },
                        new
                        {
                            Id = new Guid("9da337b0-c7ef-461a-adec-f672fd63261a"),
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = new Guid("9e714b0c-b8e8-4c92-9c05-d60c87e63202"),
                            Name = "Noruega"
                        },
                        new
                        {
                            Id = new Guid("9f132130-9d2e-4422-aa4c-2977fc79cd3f"),
                            Name = "Namíbia"
                        },
                        new
                        {
                            Id = new Guid("9ff26cde-3920-4c4c-8b52-16eaf64ff41f"),
                            Name = "Mongólia"
                        },
                        new
                        {
                            Id = new Guid("a0610786-55f3-49ef-8b42-90c840cfc0f1"),
                            Name = "Ilhas Cook"
                        },
                        new
                        {
                            Id = new Guid("a109ce39-d9d8-48fd-ab09-6cfabe84402e"),
                            Name = "Zâmbia"
                        },
                        new
                        {
                            Id = new Guid("a192071f-7dc8-459d-adc5-a8ecd6abe87a"),
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = new Guid("a313d8ee-2b67-4fd0-bd42-6bfabadd062d"),
                            Name = "Albânia"
                        },
                        new
                        {
                            Id = new Guid("a439886c-ac36-480b-afd4-7b4146320a8b"),
                            Name = "Cazaquistão"
                        },
                        new
                        {
                            Id = new Guid("a45db52c-f4b9-4854-b345-ac91dd7e8978"),
                            Name = "Canadá"
                        },
                        new
                        {
                            Id = new Guid("a5d3c095-e950-49df-a91a-cd52c6af77ef"),
                            Name = "África do Sul"
                        },
                        new
                        {
                            Id = new Guid("a7436dcd-63c3-42fb-accf-3f1b4bf5f788"),
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = new Guid("a8cc6803-cdf6-4172-b8ac-00dad15c08a5"),
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = new Guid("ab0a1443-3fd5-4ad7-a67f-550caa494d87"),
                            Name = "Palau"
                        },
                        new
                        {
                            Id = new Guid("ae42b335-56a1-4243-a1e3-413de97e2e65"),
                            Name = "Filipinas"
                        },
                        new
                        {
                            Id = new Guid("ae8a66e0-79e0-4f7c-b53a-b27ee47c3f41"),
                            Name = "Maldivas"
                        },
                        new
                        {
                            Id = new Guid("aeed0177-8054-4e01-b031-dba6d1ceb061"),
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = new Guid("af0d09ae-3e6a-49e7-89c9-63c3dc95d794"),
                            Name = "Chipre"
                        },
                        new
                        {
                            Id = new Guid("b3a1b75b-ae10-4ef1-b722-dcfedac8e1f8"),
                            Name = "Países Baixos"
                        },
                        new
                        {
                            Id = new Guid("b4786c96-85a8-4d31-ba03-8b4ea4a327ce"),
                            Name = "Líbano"
                        },
                        new
                        {
                            Id = new Guid("ba37c99f-5ce7-40dc-8808-d492d696771e"),
                            Name = "Comores"
                        },
                        new
                        {
                            Id = new Guid("bb58f66f-8e07-4031-925e-dad25ff607aa"),
                            Name = "Suécia"
                        },
                        new
                        {
                            Id = new Guid("beef65e9-1d57-4048-b3b1-1b3497b88d72"),
                            Name = "Sudão do Sul"
                        },
                        new
                        {
                            Id = new Guid("bf073adc-e649-46b9-927c-64e362ac2a61"),
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = new Guid("bfa9e3ed-2413-4bd6-b873-54d9bf1aa51d"),
                            Name = "Peru"
                        },
                        new
                        {
                            Id = new Guid("c0ffd262-5410-43be-ac27-81b6f182d9ce"),
                            Name = "Coreia do Norte"
                        },
                        new
                        {
                            Id = new Guid("c1a05781-5fa1-4c48-a3bd-8948e2b3fee2"),
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = new Guid("c27ca064-04ce-4f33-9387-95546168b3cc"),
                            Name = "Guiné Equatorial"
                        },
                        new
                        {
                            Id = new Guid("c6662ba8-1278-467e-bc28-779c9b68a9dd"),
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = new Guid("c791ca16-c456-4aee-bc90-bcb229cb664e"),
                            Name = "Irã"
                        },
                        new
                        {
                            Id = new Guid("c97fa5d6-9ab2-4eaa-8ada-6ae182e7279f"),
                            Name = "Uzbequistão"
                        },
                        new
                        {
                            Id = new Guid("cb42b93b-9c64-4c8e-823c-a018a6a7507c"),
                            Name = "Nova Zelândia"
                        },
                        new
                        {
                            Id = new Guid("cbd6b824-5339-4c90-9845-7a69c6def54c"),
                            Name = "Bahrein"
                        },
                        new
                        {
                            Id = new Guid("cc426405-6c23-4170-8679-07fad2b3712a"),
                            Name = "São Tomé e Príncipe"
                        },
                        new
                        {
                            Id = new Guid("ccbc3b65-c324-4a0b-8749-2f04b23b8a57"),
                            Name = "Sérvia"
                        },
                        new
                        {
                            Id = new Guid("d11cd9e0-48a3-4e3b-a725-ddf221c53012"),
                            Name = "Espanha"
                        },
                        new
                        {
                            Id = new Guid("d1d23014-eb3c-4e5d-b6fc-81910dd61d92"),
                            Name = "Índia"
                        },
                        new
                        {
                            Id = new Guid("d29b1936-84ba-4525-8a26-438153a954f3"),
                            Name = "Emirados Árabes Unidos"
                        },
                        new
                        {
                            Id = new Guid("d3547eeb-e657-471f-b406-696f4a170ffc"),
                            Name = "Seicheles"
                        },
                        new
                        {
                            Id = new Guid("d83a9f01-65ed-4245-9f10-c2340303719f"),
                            Name = "Benim"
                        },
                        new
                        {
                            Id = new Guid("d8eb5be3-31f8-40af-89e7-587e0a1a4b7a"),
                            Name = "Malásia"
                        },
                        new
                        {
                            Id = new Guid("d8fde566-a8d3-4021-a54d-37c091f4b9f2"),
                            Name = "Uruguai"
                        },
                        new
                        {
                            Id = new Guid("d9b8afb9-bf71-404a-90af-68fd183ea6c8"),
                            Name = "Vaticano"
                        },
                        new
                        {
                            Id = new Guid("d9c7aa53-c4b9-457e-b8fa-35096b512958"),
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = new Guid("da0f9045-4a83-41c2-932e-2a1f42b8c74b"),
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = new Guid("db74db6a-9c68-4ba1-aace-7e707f4a3435"),
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = new Guid("dbb55a9c-8b4e-4d4a-817a-2704b198606e"),
                            Name = "Croácia"
                        },
                        new
                        {
                            Id = new Guid("dc3eab46-cb02-4938-a7c8-3e9442fe864c"),
                            Name = "Dinamarca"
                        },
                        new
                        {
                            Id = new Guid("de0195cb-2f61-4a7e-912e-da5e2337a789"),
                            Name = "Quirguistão"
                        },
                        new
                        {
                            Id = new Guid("de4995e4-fcc8-4274-954b-be47b0fc337b"),
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = new Guid("df31ba5c-7ea2-476f-8616-ed9c218eaefe"),
                            Name = "Sudão"
                        },
                        new
                        {
                            Id = new Guid("df6ebe2d-7f68-4437-930d-d67a22277ec9"),
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = new Guid("dfbf5ed1-f594-478a-b348-ee8761318ed4"),
                            Name = "Gana"
                        },
                        new
                        {
                            Id = new Guid("e4270be8-4f5f-4037-85ca-79599c178279"),
                            Name = "Israel"
                        },
                        new
                        {
                            Id = new Guid("e5e3059b-a0f2-4893-840b-bb308c99fc29"),
                            Name = "Roménia"
                        },
                        new
                        {
                            Id = new Guid("e79c80e3-d3a4-49c4-ae97-3a2282a06c99"),
                            Name = "Equador"
                        },
                        new
                        {
                            Id = new Guid("e816859a-4759-4ac7-bf49-fcd87c1709e1"),
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = new Guid("e8930d06-bc98-434d-a67c-a1d297acd08d"),
                            Name = "São Vicente e Granadinas"
                        },
                        new
                        {
                            Id = new Guid("edd65bcf-f19a-45dd-93b5-1d67980de152"),
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = new Guid("ee9a08ef-25c8-4f3a-b4b8-bbdea8fd1865"),
                            Name = "França"
                        },
                        new
                        {
                            Id = new Guid("f00bdbba-998c-4d7d-a413-779727c30d2e"),
                            Name = "Palestina"
                        },
                        new
                        {
                            Id = new Guid("f09c4904-cefb-454c-94a6-f4fe586284f2"),
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = new Guid("f13d445b-5818-40a2-815d-32b6fa32bbfd"),
                            Name = "Lituânia"
                        },
                        new
                        {
                            Id = new Guid("f3059846-17a9-4529-ba55-d7c0eb4685eb"),
                            Name = "Bielorrússia"
                        },
                        new
                        {
                            Id = new Guid("f443f7e8-c28d-44cd-b300-90fff99e85f0"),
                            Name = "Grécia"
                        },
                        new
                        {
                            Id = new Guid("f4846f4a-edb0-4a90-9fb2-e440d48aa558"),
                            Name = "Brasil"
                        },
                        new
                        {
                            Id = new Guid("f5bce299-1208-4c26-926e-54493a9413bb"),
                            Name = "Mónaco"
                        },
                        new
                        {
                            Id = new Guid("f685545b-7087-4491-b699-736b9dd7c2cd"),
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = new Guid("f920bff0-6e56-43fb-8566-be40e957c108"),
                            Name = "Libéria"
                        },
                        new
                        {
                            Id = new Guid("fa893500-1221-4c38-a933-7bbec8edba7a"),
                            Name = "Letónia"
                        },
                        new
                        {
                            Id = new Guid("fad9f424-d2c8-4298-bf30-ec9ce4aceb27"),
                            Name = "Indonésia"
                        },
                        new
                        {
                            Id = new Guid("fb39f682-213b-4553-932a-f489c541ef9c"),
                            Name = "Estónia"
                        },
                        new
                        {
                            Id = new Guid("fbe6790b-d0ec-4390-9851-80f7a9f7ec84"),
                            Name = "Guiné"
                        },
                        new
                        {
                            Id = new Guid("fdaeec10-a43f-4965-985a-d8591c5a4800"),
                            Name = "Iraque"
                        },
                        new
                        {
                            Id = new Guid("ff44b793-f0e2-4c32-bb2a-30a89a849cad"),
                            Name = "Tanzânia"
                        },
                        new
                        {
                            Id = new Guid("ffb7b733-2fc2-43e8-8efc-7d67317497ed"),
                            Name = "Madagascar"
                        });
                });

            modelBuilder.Entity("SoccerTeamManager.Domain.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("VisitorTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("TournamentId");

                    b.HasIndex("VisitorTeamId");

                    b.ToTable("Match", "manager");
                });

            modelBuilder.Entity("SoccerTeamManager.Domain.Entities.MatchEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeOfOccurrence")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("TeamId");

                    b.ToTable("MatchEvent", "manager");
                });

            modelBuilder.Entity("SoccerTeamManager.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CurrentTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("CurrentTeamId");

                    b.ToTable("Player", "manager");
                });

            modelBuilder.Entity("SoccerTeamManager.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.ToTable("Team", "manager");
                });

            modelBuilder.Entity("SoccerTeamManager.Domain.Entities.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<double>("Prize")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tournament", "manager");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbaedea6-04f8-4343-a832-314482933a1b"),
                            CreatedAt = new DateTime(2022, 7, 24, 17, 26, 1, 444, DateTimeKind.Local).AddTicks(1026),
                            Name = "Amistoso",
                            Prize = 0.0
                        });
                });

            modelBuilder.Entity("SoccerTeamManager.Domain.Entities.TournamentTeam", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TeamId", "TournamentId");

                    b.HasIndex("TournamentId");

                    b.ToTable("TounamentTeam", "manager");
                });

            modelBuilder.Entity("SoccerTeamManager.Domain.Entities.Transfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Ammount")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DestinationTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OriginTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DestinationTeamId");

                    b.HasIndex("OriginTeamId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Transfer", "manager");
                });

            modelBuilder.Entity("SoccerTeamManager.Domain.Entities.Match", b =>
                {
                    b.HasOne("SoccerTeamManager.Domain.Entities.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SoccerTeamManager.Domain.Entities.Tournament", null)
                        .WithMany("Matches")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoccerTeamManager.Domain.Entities.Team", "VisitorTeam")
                        .WithMany()
                        .HasForeignKey("VisitorTeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HomeTeam");

                    b.Navigation("VisitorTeam");
                });

            modelBuilder.Entity("SoccerTeamManager.Domain.Entities.MatchEvent", b =>
                {
                    b.HasOne("SoccerTeamManager.Domain.Entities.Match", null)
                        .WithMany("MatchEvents")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoccerTeamManager.Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("SoccerTeamManager.Domain.Entities.Player", b =>
                {
                    b.HasOne("SoccerTeamManager.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoccerTeamManager.Domain.Entities.Team", null)
                        .WithMany("Players")
                        .HasForeignKey("CurrentTeamId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("SoccerTeamManager.Domain.Entities.TournamentTeam", b =>
                {
                    b.HasOne("SoccerTeamManager.Domain.Entities.Team", null)
                        .WithMany("TournamentTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SoccerTeamManager.Domain.Entities.Tournament", null)
                        .WithMany("TournamentTeams")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SoccerTeamManager.Domain.Entities.Transfer", b =>
                {
                    b.HasOne("SoccerTeamManager.Domain.Entities.Team", "DestinationTeam")
                        .WithMany()
                        .HasForeignKey("DestinationTeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SoccerTeamManager.Domain.Entities.Team", "OriginTeam")
                        .WithMany()
                        .HasForeignKey("OriginTeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SoccerTeamManager.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DestinationTeam");

                    b.Navigation("OriginTeam");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("SoccerTeamManager.Domain.Entities.Match", b =>
                {
                    b.Navigation("MatchEvents");
                });

            modelBuilder.Entity("SoccerTeamManager.Domain.Entities.Team", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("TournamentTeams");
                });

            modelBuilder.Entity("SoccerTeamManager.Domain.Entities.Tournament", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("TournamentTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
