using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SoccerTeamManager.Domain.Entities;

namespace SoccerTeamManager.Infra.Data.Mappings
{
    public class CountryMapping : IEntityTypeConfiguration<Country>
    {
        public void Configure(EntityTypeBuilder<Country> builder)
        {
            builder.HasKey(p => p.Id);

            builder.Property(p => p.Id).IsRequired();
            builder.Property(p => p.Name).HasMaxLength(256).IsRequired();
            builder.Ignore(p => p.CreatedAt);
            builder.Ignore(p => p.UpdatedAt);

            builder.HasMany(c => c.Players)
                .WithOne(p => p.Country)
                .HasForeignKey(p => p.CountryId);

            builder.HasData(
                new Country("Afeganistão"),
                new Country("África do Sul"),
                new Country("Albânia"),
                new Country("Alemanha"),
                new Country("Andorra"),
                new Country("Angola"),
                new Country("Antígua e Barbuda"),
                new Country("Arábia Saudita"),
                new Country("Argélia"),
                new Country("Argentina"),
                new Country("Arménia"),
                new Country("Austrália"),
                new Country("Áustria"),
                new Country("Azerbaijão"),
                new Country("Bahamas"),
                new Country("Bahrein"),
                new Country("Bangladesh"),
                new Country("Barbados"),
                new Country("Bélgica"),
                new Country("Belize"),
                new Country("Benim"),
                new Country("Bielorrússia"),
                new Country("Bolívia"),
                new Country("Bósnia e Herzegovina"),
                new Country("Botswana"),
                new Country("Brasil"),
                new Country("Brunei"),
                new Country("Bulgária"),
                new Country("Burquina Fasso"),
                new Country("Burundi"),
                new Country("Butão"),
                new Country("Cabo Verde"),
                new Country("Camarões"),
                new Country("Camboja"),
                new Country("Canadá"),
                new Country("Catar"),
                new Country("Cazaquistão"),
                new Country("Chade"),
                new Country("Chéquia"),
                new Country("Chile"),
                new Country("China"),
                new Country("Chipre"),
                new Country("Colômbia"),
                new Country("Comores"),
                new Country("Congo"),
                new Country("Coreia do Norte"),
                new Country("Coreia do Sul"),
                new Country("Costa do Marfim"),
                new Country("Costa Rica"),
                new Country("Croácia"),
                new Country("Cuba"),
                new Country("Dinamarca"),
                new Country("Djibouti"),
                new Country("Domínica"),
                new Country("Egito"),
                new Country("El Salvador"),
                new Country("Emirados Árabes Unidos"),
                new Country("Equador"),
                new Country("Eritreia"),
                new Country("Eslováquia"),
                new Country("Eslovénia"),
                new Country("Espanha"),
                new Country("Estados Federados da Micronésia"),
                new Country("Estados Unidos"),
                new Country("Estónia"),
                new Country("Eswatini"),
                new Country("Etiópia"),
                new Country("Fiji"),
                new Country("Filipinas"),
                new Country("Finlândia"),
                new Country("França"),
                new Country("Gabão"),
                new Country("Gâmbia"),
                new Country("Gana"),
                new Country("Geórgia"),
                new Country("Granada"),
                new Country("Grécia"),
                new Country("Guatemala"),
                new Country("Guiana"),
                new Country("Guiné"),
                new Country("Guiné Equatorial"),
                new Country("Guiné-Bissau"),
                new Country("Haiti"),
                new Country("Honduras"),
                new Country("Hungria"),
                new Country("Iémen"),
                new Country("Ilhas Cook"),
                new Country("Ilhas Marshall"),
                new Country("Ilhas Salomão"),
                new Country("Índia"),
                new Country("Indonésia"),
                new Country("Irã"),
                new Country("Iraque"),
                new Country("Irlanda"),
                new Country("Islândia"),
                new Country("Israel"),
                new Country("Itália"),
                new Country("Jamaica"),
                new Country("Japão"),
                new Country("Jordânia"),
                new Country("Kiribati"),
                new Country("Kosovo"),
                new Country("Kuwait"),
                new Country("Laos"),
                new Country("Lesoto"),
                new Country("Letónia"),
                new Country("Líbano"),
                new Country("Libéria"),
                new Country("Líbia"),
                new Country("Liechtenstein"),
                new Country("Lituânia"),
                new Country("Luxemburgo"),
                new Country("Macedônia do Norte"),
                new Country("Madagascar"),
                new Country("Malásia"),
                new Country("Malawi"),
                new Country("Maldivas"),
                new Country("Mali"),
                new Country("Malta"),
                new Country("Marrocos"),
                new Country("Maurícia"),
                new Country("Mauritânia"),
                new Country("México"),
                new Country("Moçambique"),
                new Country("Moldova"),
                new Country("Mónaco"),
                new Country("Mongólia"),
                new Country("Montenegro"),
                new Country("Myanmar"),
                new Country("Namíbia"),
                new Country("Nauru"),
                new Country("Nepal"),
                new Country("Nicarágua"),
                new Country("Níger"),
                new Country("Nigéria"),
                new Country("Niue"),
                new Country("Noruega"),
                new Country("Nova Zelândia"),
                new Country("Oman"),
                new Country("Países Baixos"),
                new Country("Palau"),
                new Country("Palestina"),
                new Country("Panamá"),
                new Country("Papua-Nova Guiné"),
                new Country("Paquistão"),
                new Country("Paraguai"),
                new Country("Peru"),
                new Country("Polónia"),
                new Country("Portugal"),
                new Country("Quénia"),
                new Country("Quirguistão"),
                new Country("Reino Unido"),
                new Country("República Centro-Africana"),
                new Country("República Democrática do Congo"),
                new Country("República Dominicana"),
                new Country("Roménia"),
                new Country("Ruanda"),
                new Country("Rússia"),
                new Country("Samoa"),
                new Country("San Marino"),
                new Country("São Cristóvão e Nevis"),
                new Country("São Tomé e Príncipe"),
                new Country("São Vicente e Granadinas"),
                new Country("Seicheles"),
                new Country("Senegal"),
                new Country("Serra Leoa"),
                new Country("Sérvia"),
                new Country("Singapura"),
                new Country("Síria"),
                new Country("Somália"),
                new Country("Sri Lanka"),
                new Country("Sudão"),
                new Country("Sudão do Sul"),
                new Country("Suécia"),
                new Country("Suíça"),
                new Country("Suriname"),
                new Country("Tailândia"),
                new Country("Taiwan"),
                new Country("Tajiquistão"),
                new Country("Tanzânia"),
                new Country("Timor-Leste"),
                new Country("Togo"),
                new Country("Tonga"),
                new Country("Trinidad e Tobago"),
                new Country("Tunísia"),
                new Country("Turquemenistão"),
                new Country("Turquia"),
                new Country("Tuvalu"),
                new Country("Ucrânia"),
                new Country("Uganda"),
                new Country("Uruguai"),
                new Country("Uzbequistão"),
                new Country("Vanuatu"),
                new Country("Vaticano"),
                new Country("Venezuela"),
                new Country("Vietname"),
                new Country("Zâmbia"),
                new Country("Zimbabwe")
                );
        }
    }
}
